### ISSUE TITLE
Broken link for "SCSS color values"

### ISSUE THREAD

**Issue by rlorenzo** [uclaioes/ucla-design-system#2]
**Describe the bug**
404 error on link "SCSS color values".

**To Reproduce**
1. Go to https://uclaioes.github.io/ucla-design-system/
2. Click on "SCSS color values".
3. Get 404 error

**Expected behavior**
A link with the colors in SCSS format

**Screehshot**
![Screen Shot 2019-06-03 at 5 02 00 PM](https://user-images.githubusercontent.com/349765/58842080-6b139900-8621-11e9-88e0-7d9a801006e2.png)

**Comment by scottgruber** [comment]
Here is a gist of it [scss color values](https://gist.github.com/scottgruber/b113410dccf16b9722a92dde22f3d689). 

Or you can get to the file [in the repository](https://github.com/uclaioes/ucla-design-system). 

I'd like to consolidate a [ucla color repo](https://github.com/uclaioes/ucla-color-palette/) into the design system, but haven't deprecated it yet. Maybe that helps too? I'd like to avoid linking direct to commits in the code.
